tap "argon/mas"
tap "ariga/tap"
tap "budougumi0617/lsas"
tap "bufbuild/buf"
tap "cj-bc/cj-bc"
tap "cue-lang/tap"
tap "earthly/earthly"
tap "go-delve/delve"
tap "go-swagger/go-swagger"
tap "golangci/tap"
tap "goldeneggg/lsec2"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "ktr0731/evans"
tap "osx-cross/avr"
tap "px4/px4"
tap "rcmdnk/file"
tap "sanemat/font"
tap "weaveworks/tap"
brew "openssl@1.1"
brew "readline"
brew "ansible"
brew "antigen"
brew "anyenv"
brew "aspell"
brew "autoconf"
brew "automake"
brew "boost"
brew "avrdude"
brew "awk", link: false
brew "aws-iam-authenticator", link: false
brew "awscli"
brew "python@3.10"
brew "azure-cli"
brew "bat"
brew "freetype"
brew "fontconfig"
brew "glib"
brew "pkg-config"
brew "pixman"
brew "cairo"
brew "gflags"
brew "circleci"
brew "clang-format"
brew "cmake"
brew "colordiff"
brew "corepack"
brew "coreutils"
brew "csshx"
brew "ctags"
brew "curl"
brew "libsodium"
brew "czmq"
brew "go"
brew "dfu-programmer"
brew "direnv"
brew "elixir"
brew "libtool"
brew "libevent"
brew "emacs"
brew "exa"
brew "harfbuzz"
brew "libass"
brew "pango"
brew "fontforge"
brew "fzf"
brew "gawk", link: false
brew "gh"
brew "ghq"
brew "git"
brew "git-secrets"
brew "glide"
brew "gnu-getopt"
brew "gnu-sed"
brew "gnupg"
brew "gobject-introspection"
brew "graphviz"
brew "helm"
brew "helmfile"
brew "lua"
brew "highlight"
brew "httpd"
brew "hub"
brew "hugo"
brew "jq"
brew "libmagic"
brew "mas"
brew "mecab"
brew "mecab-ipadic"
brew "memcached", restart_service: true
brew "mercurial"
brew "mono", link: false
brew "protobuf"
brew "mysql"
brew "mysql@5.7"
brew "neovim"
brew "nkf"
brew "node-build"
brew "node@18", link: true
brew "opencv"
brew "pcre"
brew "peco"
brew "reattach-to-user-namespace"
brew "redis"
brew "ripgrep"
brew "ruby-build"
brew "shellcheck"
brew "shtool"
brew "sops"
brew "stern"
brew "stress"
brew "tfenv"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "tree"
brew "up"
brew "vim"
brew "vips"
brew "watch"
brew "wget"
brew "xerces-c"
brew "zplug"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "ariga/tap/atlas"
brew "budougumi0617/lsas/lsas"
brew "bufbuild/buf/buf"
brew "cue-lang/tap/cue"
brew "earthly/earthly/earthly"
brew "golangci/tap/golangci-lint"
brew "goldeneggg/lsec2/lsec2"
brew "ktr0731/evans/evans"
brew "osx-cross/avr/avr-gcc@9"
brew "px4/px4/gcc-arm-none-eabi"
brew "rcmdnk/file/brew-file"
brew "sanemat/font/ricty"
brew "weaveworks/tap/eksctl"
mas "Be Focused", id: 973134470
mas "BetterSnapTool", id: 417375580
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Mini Calendar", id: 1088779979
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Skitch", id: 425955336
mas "Slack", id: 803453959
mas "The Unarchiver", id: 425424353
mas "Toggl Track", id: 957734279
