
# tap repositories and their packages

tap caskroom/cask
cask appcleaner
cask atom
cask dropbox
cask eclipse-java
cask google-chrome
cask google-japanese-ime
cask hammerspoon
cask iterm2
cask java
cask kindle
cask microsoft-azure-storage-explorer
cask skitch
cask visual-studio-code

tap go-delve/delve
brew delve

tap go-swagger/go-swagger
brew go-swagger

tap homebrew/bundle

tap homebrew/core
brew ansible
brew autoconf
brew azure-cli
brew boost
brew cairo
brew ctags
brew czmq
brew elixir
brew erlang
brew fontconfig
brew fontforge
brew freetype
brew gdbm
brew gettext
brew ghq
brew git
brew glib
brew glide
brew gnu-sed
brew go
brew gobject-introspection
brew gradle
brew harfbuzz
brew highlight
brew hub
brew icu4c
brew jpeg
brew libevent
brew libffi
brew libpng
brew libsodium
brew libtiff
brew libtool
brew libyaml
brew lua
brew mas
brew mercurial
brew mysql
brew node
brew openssl
brew openssl@1.1
brew pango
brew pcre
brew peco
brew pixman
brew pkg-config
brew python
brew rbenv
brew readline
brew reattach-to-user-namespace
brew ruby-build
brew shellcheck
brew sqlite
brew stress
brew tig
brew tmux
brew tree
brew vim --with-lua
brew wget
brew wxmac
brew xerces-c
brew zeromq
brew zplug
brew zsh

tap phinze/cask

tap rcmdnk/file
brew brew-file

tap sanemat/font
brew ricty

# App Store applications
appstore 405843582 Alfred (1.2)
appstore 403858460 EchofonLite (1.8.7)
appstore 647697434 Free Fonts (7.0)
appstore 682658836 GarageBand (10.1.6)
appstore 409183694 Keynote (7.0.5)
appstore 896624060 Kobito (2.3.8)
appstore 539883307 LINE (4.11.1)
appstore 921923693 LibreOffice Vanilla (5.2.3005)
appstore 409203825 Numbers (4.0.5)
appstore 409201541 Pages (6.0.5)
appstore 863486266 SketchBook (8.3.1)
appstore 803453959 Slack (2.4.1)
appstore 585829637 Todoist (6.3.19)
appstore 408981434 iMovie (10.1.4)
appstore 408981381 iPhoto (9.6.1)
