[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = '/usr/local/opt/fzf'

[[plugins]]
repo = '/usr/local/opt/fzf'
if = 'isdirectory("/usr/local/opt/fzf")'

[[plugins]]
repo = '~/.fzf'
if = 'isdirectory(expand("~/.fzf"))'

#####################
#  Utilities
#####################
[[plugins]]
repo = 'scrooloose/nerdtree'


#####################
#  For Git
#####################
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'kristijanhusak/defx-git'

#####################
#  For vim-lsp settings
#####################
[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-snippets'

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-ultisnips'


#####################
# For Go
#####################
[[plugins]]
repo = 'mattn/vim-goimports'

#####################
# For Visual
# need font settings
# brew tap homebrew/cask-fonts
# brew cask install font-hack-nerd-font
# terminal setting https://qiita.com/arks22/items/9688ec7f4cb43444e9d9#%E3%82%A2%E3%82%A4%E3%82%B3%E3%83%B3
#####################
[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kristijanhusak/defx-icons'
